wd_cs_domain_admin_snippet:
    resource: "@WdCsDomainBundle/Resources/config/routing/snippet.yml"
    prefix:   /admin/snippet

wd_cs_domain_admin_author:
    resource: "@WdCsDomainBundle/Resources/config/routing/author.yml"
    prefix:   /admin/author

wd_cs_domain_admin_programminglanguage:
    resource: "@WdCsDomainBundle/Resources/config/routing/programminglanguage.yml"
    prefix:   /admin/programminglanguage

wd_cs_domain_homepage:
    path:     /
    defaults: { _controller: WdCsDomainBundle:Dashboard:index }
