fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

wd_cs_themes_core3rd_party:
    resource: "@WdCsThemesCore3rdPartyBundle/Resources/config/routing.yml"
    prefix:   /

wd_cs_themes_core_theme:
    resource: "@WdCsThemesCoreThemeBundle/Resources/config/routing.yml"
    prefix:   /

wd_cs_core:
    resource: "@WdCsCoreBundle/Resources/config/routing.yml"
    prefix:   /
