wd_cs_domain:
    resource: "@WdCsDomainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dh_core:
    resource: "@DhCoreBundle/Resources/config/routing.yml"
    prefix:   /

dh_themes_core3rd_party:
    resource: "@DhThemesCore3rdPartyBundle/Resources/config/routing.yml"
    prefix:   /

dh_themes_core_theme:
    resource: "@DhThemesCoreThemeBundle/Resources/config/routing.yml"
    prefix:   /

