wd_cs_admin_config:
    path:     /
    defaults: { _controller: "WdCsCoreBundle:Config:index" }

wd_cs_admin_config_show:
    path:     /{id}/show
    defaults: { _controller: "WdCsCoreBundle:Config:show" }

wd_cs_admin_config_new:
    path:     /new
    defaults: { _controller: "WdCsCoreBundle:Config:new" }

wd_cs_admin_config_create:
    path:     /create
    defaults: { _controller: "WdCsCoreBundle:Config:create" }
    methods:  POST

wd_cs_admin_config_edit:
    path:     /{id}/edit
    defaults: { _controller: "WdCsCoreBundle:Config:edit" }

wd_cs_admin_config_update:
    path:     /{id}/update
    defaults: { _controller: "WdCsCoreBundle:Config:update" }
    methods:  [POST, PUT]

wd_cs_admin_config_delete:
    path:     /{id}/delete
    defaults: { _controller: "WdCsCoreBundle:Config:delete" }
    methods:  [POST, DELETE]
