wd_cs_admin_tag:
    path:     /
    defaults: { _controller: "WdCsCoreBundle:Tag:index" }

wd_cs_admin_tag_show:
    path:     /{id}/show
    defaults: { _controller: "WdCsCoreBundle:Tag:show" }

wd_cs_admin_tag_new:
    path:     /new
    defaults: { _controller: "WdCsCoreBundle:Tag:new" }

wd_cs_admin_tag_create:
    path:     /create
    defaults: { _controller: "WdCsCoreBundle:Tag:create" }
    methods:  POST

wd_cs_admin_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "WdCsCoreBundle:Tag:edit" }

wd_cs_admin_tag_update:
    path:     /{id}/update
    defaults: { _controller: "WdCsCoreBundle:Tag:update" }
    methods:  [POST, PUT]

wd_cs_admin_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "WdCsCoreBundle:Tag:delete" }
    methods:  [POST, DELETE]
