dh_admin_author:
    path:     /
    defaults: { _controller: "WdCsDomainBundle:Author:index" }

dh_admin_author_show:
    path:     /{id}/show
    defaults: { _controller: "WdCsDomainBundle:Author:show" }

dh_admin_author_new:
    path:     /new
    defaults: { _controller: "WdCsDomainBundle:Author:new" }

dh_admin_author_create:
    path:     /create
    defaults: { _controller: "WdCsDomainBundle:Author:create" }
    methods:  POST

dh_admin_author_edit:
    path:     /{id}/edit
    defaults: { _controller: "WdCsDomainBundle:Author:edit" }

dh_admin_author_update:
    path:     /{id}/update
    defaults: { _controller: "WdCsDomainBundle:Author:update" }
    methods:  [POST, PUT]

dh_admin_author_delete:
    path:     /{id}/delete
    defaults: { _controller: "WdCsDomainBundle:Author:delete" }
    methods:  [POST, DELETE]
