wd_cs_core_admin_tag:
    resource: "@WdCsCoreBundle/Resources/config/routing/tag.yml"
    prefix:   /admin/tag

wd_cs_core_homepage:
    path:     /
    defaults: { _controller: WdCsCoreBundle:Default:index }
